/**
 * KhanNetra Vision smoke test
 * Run: node test_vision.js
 */
'use strict';

require('dotenv').config();
const http = require('http');

function post(path, body, token) {
  return new Promise((resolve, reject) => {
    const data = JSON.stringify(body);
    const req  = http.request({
      host: 'localhost', port: 5000, path,
      method: 'POST',
      headers: {
        'Content-Type':   'application/json',
        'Content-Length': Buffer.byteLength(data),
        ...(token ? { Authorization: 'Bearer ' + token } : {}),
      },
    }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        try { resolve({ s: res.statusCode, b: JSON.parse(d) }); }
        catch { resolve({ s: res.statusCode, b: { raw: d.slice(0, 200) } }); }
      });
    });
    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

function getReq(path, token) {
  return new Promise((resolve, reject) => {
    const req = http.request({
      host: 'localhost', port: 5000, path,
      method: 'GET',
      headers: token ? { Authorization: 'Bearer ' + token } : {},
    }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        try { resolve({ s: res.statusCode, b: JSON.parse(d) }); }
        catch { resolve({ s: res.statusCode, b: { raw: d.slice(0, 200) } }); }
      });
    });
    req.on('error', reject);
    req.end();
  });
}

function postMultipart(path, token, imageBuffer, filename) {
  return new Promise((resolve, reject) => {
    const boundary = 'KNBoundary' + Date.now();
    const CRLF = '\r\n';

    // Build multipart body
    const header1 = Buffer.from(
      '--' + boundary + CRLF +
      'Content-Disposition: form-data; name="image"; filename="' + filename + '"' + CRLF +
      'Content-Type: image/jpeg' + CRLF + CRLF
    );
    const header2 = Buffer.from(
      CRLF + '--' + boundary + CRLF +
      'Content-Disposition: form-data; name="mine_type"' + CRLF + CRLF +
      'default' + CRLF +
      '--' + boundary + '--' + CRLF
    );
    const body = Buffer.concat([header1, imageBuffer, header2]);

    const req = http.request({
      host: 'localhost', port: 5000, path,
      method: 'POST',
      headers: {
        'Content-Type':   'multipart/form-data; boundary=' + boundary,
        'Content-Length': body.length,
        Authorization:    'Bearer ' + token,
      },
    }, res => {
      let d = '';
      res.on('data', c => d += c);
      res.on('end', () => {
        try { resolve({ s: res.statusCode, b: JSON.parse(d) }); }
        catch { resolve({ s: res.statusCode, b: { raw: d.slice(0, 300) } }); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

// Minimal valid JPEG (200×200 grey square, generated by sharp)
const MINIMAL_JPEG = require('fs').readFileSync(require('path').join(__dirname, 'test_frame.jpg'));

async function run() {
  console.log('\n═══════════════════════════════════════════');
  console.log(' KhanNetra Safety Vision — Smoke Test');
  console.log('═══════════════════════════════════════════\n');

  // ── Step 1: Login
  console.log('1. Logging in as admin...');
  const login = await post('/api/v1/auth/login', {
    email:    'admin@khannetra.gov.in',
    password: 'KhanNetra@2024',
  });
  if (!login.b.success) {
    console.error('   ❌ Login failed:', login.b.message);
    return;
  }
  const token = login.b.data.token;
  console.log('   ✅ Login OK, token obtained');

  // ── Step 2: Vision health
  console.log('\n2. Checking vision health...');
  const health = await getReq('/api/v1/vision/health', token);
  console.log('   Status:', health.s);
  console.log('   Backend:', health.b.model_backend);
  console.log('   Gemini API key:', health.b.api_key_status?.gemini);
  console.log('   Overall:', health.b.status);

  // ── Step 3: PPE reference
  console.log('\n3. Fetching PPE reference...');
  const ref = await getReq('/api/v1/vision/ppe-reference', token);
  const itemCount = Object.keys(ref.b.data?.ppe_items || {}).length;
  console.log('   PPE items configured:', itemCount);

  // ── Step 4: POST detect with minimal JPEG
  console.log('\n4. Sending scan request with test image...');
  const detect = await postMultipart('/api/v1/vision/detect', token, MINIMAL_JPEG, 'test.jpg');
  console.log('   HTTP status:', detect.s);

  if (detect.b.success === true) {
    console.log('   ✅ Scan SUCCEEDED');
    console.log('   Workers detected:', detect.b.site_summary?.total_workers ?? 'N/A');
    console.log('   Site status:', detect.b.site_summary?.site_status ?? 'N/A');
    console.log('   Model used:', detect.b.model_info?.name ?? 'N/A');
    console.log('   Processing ms:', detect.b.processing_ms ?? 'N/A');
    console.log('   Scene:', detect.b.scene_info?.description ?? 'N/A');
  } else if (detect.b.success === false) {
    console.log('   ⚠️  Scan returned error:', detect.b.message);
    // Error message (not "No JSON found") means the fix worked — the error is now descriptive
    if (detect.b.message && !detect.b.message.includes('No JSON found') && !detect.b.message.includes('No valid JSON')) {
      console.log('   ✅ "No JSON found" bug is FIXED — error is now descriptive');
    }
  } else {
    console.log('   Raw response:', JSON.stringify(detect.b).slice(0, 300));
  }

  console.log('\n═══════════════════════════════════════════');
  console.log(' Test complete');
  console.log('═══════════════════════════════════════════\n');
}

run().catch(err => {
  console.error('\n❌ Test script error:', err.message);
  process.exit(1);
});
